application: amber-goatstone
version: 1
runtime: go
api_version: go1

handlers:

- url: /css
  static_dir: public/css
  mime_type: text/css

- url: /js
  static_dir: public/js
  mime_type: application/javascript

- url: /datum
  static_dir: datum

- url: /image
  static_dir: public/image

- url: /about/*
  static_files:  about/index.html
  upload:  about/index.html

- url: /node_modules
  static_dir: node_modules

- url: /src
  static_dir: src

- url: /test/lib
  static_dir: tests/lib/jasmine-2.0.2

- url: /test
  static_dir: test

- url: /test/spec
  static_dir: tests/spec
  mime_type: application/javascript

- url: /.*
  script: _go_app