application: lime-goatstone
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /css
  static_dir: css
  mime_type: text/css

- url: /js
  static_dir: js
  mime_type: application/javascript

- url: /datum
  static_dir: datum

- url: /test/*
  static_files:  tests/SpecRunner.html
  upload:  tests/SpecRunner.html
  # static_files:  index.html
  # upload:  index.html

- url: /test/spec
  static_dir: tests/spec
  mime_type: application/javascript

- url: /test/lib
  static_dir: jasmine/lib/jasmine-2.0.0

- url: /.*
  script: _go_app